spring:
  application:
    name: choco-planner

  doc:
    api-docs:
      path: /api-docs


  datasource:
    url: jdbc:mysql://choco-planner-db.cf8uu8sca40i.ap-northeast-2.rds.amazonaws.com:3306/choco_planner_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=false
    username: admin
    password: 8594wotj

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      audio:
        transcription:
          options:
            model: whisper-1
            response-format: json  # json, text, srt, verbose_json or vtt
            temperature: 0  # sampling temperature, between 0 and 1
            timestamp_granularities: segment  # segment and word (either or both)

  mvc:
    static-path-pattern: /static/**

springdoc:
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    url: /api-docs
    disable-swagger-default-url: true
    operations-sorter: method


server:
  port: 8000

