spring:
  application:
    name: choco-planner

  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

  datasource:
    url: jdbc:mysql://choco-planner-db.cf8uu8sca40i.ap-northeast-2.rds.amazonaws.com:3306/choco_planner_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=false
    username: admin
    password: 8594wotj

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      audio:
        transcription:
          options:
            model: whisper-1
            response-format: json  # json, text, srt, verbose_json or vtt
            temperature: 0  # sampling temperature, between 0 and 1
            timestamp_granularities: segment  # segment and word (either or both)

  mvc:
    static-path-pattern: /static/**

server:
  port: 8000
